name: 'DefectDojo Import Report Scan'
description: >
    Import scan result into DefectDojo
inputs:
  token:
    description: > 
        (string($date)) The personal access token used to access the API.
    required: true
  defectdojo_url:
    description: > 
        (string) The DefectDojo base url. Example: https://defectdojo.domain.com
    required: true
  defectdojo_endpoint:
    description: >
        (string) The DefectDojo import-scan endpoint. Default: /api/v2/import-scan/
    default: '/api/v2/import-scan/'
  scan_date:
    description: >
        (string) The Default value: yyyy-mm-dd ( Current date )
    default: ''
  minimum_severity:
    description: > 
        (string) Available values : Info, Low, Medium, High, Critical. Default value: Info
    default: 'Info'
  active:
    description: > 
        (boolean) Boolean. Default value: true
    default: true
  verified:
    description: > 
        (boolean) Boolean. Default value: true
    default: true
  scan_type:
    description: > 
        (string) Available values : Acunetix Scan, Acunetix360 Scan, Anchore Engine Scan, Anchore Enterprise Policy Check, Anchore Grype, AppSpider Scan, Aqua Scan, Arachni Scan, AuditJS Scan, AWS Prowler Scan, AWS Scout2 Scan, AWS Security Hub Scan, Azure Security Center Recommendations Scan, Bandit Scan, Blackduck Component Risk, Blackduck Hub Scan, Brakeman Scan, BugCrowd Scan, Bundler-Audit Scan, Burp Enterprise Scan, Burp REST API, Burp Scan, CargoAudit Scan, CCVS Report, Checkmarx OSA, Checkmarx Scan, Checkmarx Scan detailed, Checkov Scan, Choctaw Hog Scan, Clair Klar Scan, Clair Scan, Cloudsploit Scan, Cobalt.io API Import, Cobalt.io Scan, Contrast Scan, Coverity API, Crashtest Security JSON File, Crashtest Security XML File, CredScan Scan, CycloneDX Scan, DawnScanner Scan, Dependency Check Scan, Dependency Track Finding Packaging Format (FPF) Export, Detect-secrets Scan, Dockle Scan, DrHeader JSON Importer, DSOP Scan, ESLint Scan, Fortify Scan, Generic Findings Import, Github Vulnerability Scan, GitLab API Fuzzing Report Scan, GitLab Container Scan, GitLab DAST Report, GitLab Dependency Scanning Report, GitLab SAST Report, GitLab Secret Detection Report, Gitleaks Scan, Gosec Scanner, HackerOne Cases, Hadolint Dockerfile check, Harbor Vulnerability Scan, HuskyCI Report, IBM AppScan DAST, Immuniweb Scan, IntSights Report, JFrog Xray Scan, JFrog Xray Unified Scan, KICS Scan, Kiuwan Scan, kube-bench Scan, Meterian Scan, Microfocus Webinspect Scan, MobSF Scan, Mobsfscan Scan, Mozilla Observatory Scan, Nessus Scan, Nessus WAS Scan, Netsparker Scan, Nexpose Scan, Nikto Scan, Nmap Scan, Node Security Platform Scan, NPM Audit Scan, Nuclei Scan, Openscap Vulnerability Scan, OpenVAS CSV, ORT evaluated model Importer, OssIndex Devaudit SCA Scan Importer, Outpost24 Scan, PHP Security Audit v2, PHP Symfony Security Check, PMD Scan, Qualys Infrastructure Scan (WebGUI XML), Qualys Scan, Qualys Webapp Scan, Retire.js Scan, Risk Recon API Importer, Safety Scan, SARIF, Scantist Scan, Scout Suite Scan, Semgrep JSON Report, SKF Scan, Snyk Scan, SonarQube API Import, SonarQube Scan, SonarQube Scan detailed, Sonatype Application Scan, SpotBugs Scan, SSL Labs Scan, Sslscan, SSLyze 3 Scan (JSON), Sslyze Scan, Terrascan Scan, Testssl Scan, TFSec Scan, Trivy Scan, Trufflehog Scan, Trufflehog3 Scan, Trustwave Fusion API Scan, Trustwave Scan (CSV), Twistlock Image Scan, VCG Scan, Veracode Scan, Wapiti Scan, WFuzz JSON report, WhiteHat Sentinel, Whitesource Scan, Wpscan, Xanitizer Scan, Yarn Audit Scan, ZAP Scan
    required: true
  endpoint_to_add:
    description: > 
        (integer) Endpoint id.
    default: ''
  file:
    description: > 
        (string) File path.
    required: true
  engagement:
    description: > 
        (integer) Engagement id.
    required: true
  lead:
    description: > 
        (integer) Lead id.
    default: ''
  tags:
    description: > 
        (array[string]) Tag array.
    default: ''
  close_old_findings:
    description: > 
        (boolean) Boolean. Default value: false.
    default: false
  push_to_jira:
    description: > 
        (boolean) Boolean. Default value: false.
    default: false
  environment:
    description: > 
        (string) Environment name.
    default: ''
  version:
    description: > 
        (string) Project version.
    default: ''
  build_id:
    description: > 
        (string) Build id.
    default: ''
  branch_tag:
    description: > 
        (string) Branch tag.
    default: ''
  commit_hash:
    description: > 
        (string) Commit hash.
    default: ''
  sonarqube_config:
    description: > 
        (integer) Sonarqube config id.
    default: ''
  cobaltio_config:
    description: > 
        (integer) Cobaltio config id.
    default: ''
  group_by:
    description: > 
        (string) Choose an option to automatically group new findings by the chosen option. Available values: component_name, component_name+component_version, file_path. Default value: component_name+component_version
    default: 'component_name+component_version'
outputs:
  response:
    description: 'DefectDojo publish result'
    value: ${{ steps.import.outputs.response }}
runs:
  using: 'composite'
  steps:
    - id: import
      run: |
        ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_DEFECTDOJO_URL: ${{ inputs.defectdojo_url }}
        INPUT_DEFECTDOJO_ENDPOINT: ${{ inputs.defectdojo_endpoint }}
        INPUT_SCAN_DATE: ${{ inputs.scan_date }}
        INPUT_MINIMUM_SEVERITY: ${{ inputs.minimum_severity }}
        INPUT_ACTIVE: ${{ inputs.active }}
        INPUT_VERIFIED: ${{ inputs.verified }}
        INPUT_SCAN_TYPE: ${{ inputs.scan_type }}
        INPUT_ENDPOINT_TO_ADD: ${{ inputs.endpoint_to_add }}
        INPUT_FILE: ${{ github.workspace}}/${{ inputs.file }}
        INPUT_ENGAGEMENT: ${{ inputs.engagement }}
        INPUT_LEAD: ${{ inputs.lead }}
        INPUT_TAGS: ${{ inputs.tags }}
        INPUT_CLOSE_OLD_FINDINGS: ${{ inputs.close_old_findings }}
        INPUT_PUSH_TO_JIRA: ${{ inputs.push_to_jira }}
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_BUILD_ID: ${{ inputs.build_id }}
        INPUT_BRANCH_TAG: ${{ inputs.branch_tag }}
        INPUT_COMMIT_HASH: ${{ inputs.commit_hash }}
        INPUT_SONARQUBE_CONFIG: ${{ inputs.sonarqube_config }}
        INPUT_COBALTIO_CONFIG: ${{ inputs.cobaltio_config }}
        INPUT_GROUP_BY: ${{ inputs.group_by }}

branding:
  icon: 'target'
  color: 'gray-dark'
